language: python 

install:   
  - pip3 install flask
  - pip3 install gunicorn
  - pip3 install flask_wtf
  - pip3 install numpy
  - pip3 install pillow
  - pip3 install matplotlib
  - pip3 install requests

script:   
  - cd picture-crusade   
  - bash st.sh 
